name: Checks

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # prerequisites
        python -m pip install --group dev
        # install dependencies
        pip install -e .
        # show installed packages
        pip freeze
    - name: Lint with flake8
      run: |
        flake8 --exclude _version.py .
    - name: Test with pytest (numpy v1)
      run: |
        pip install numpy==1.26.4
        pytest tests
    - name: Test with pytest (numpy v2)
      run: |
        pip install numpy==2.4.6
        pytest tests
